# Generated by Django 2.2 on 2020-05-07 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='timeStamp',
            new_name='creationTimeStamp',
        ),
        migrations.AddField(
            model_name='reminder',
            name='dueTimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
