# Generated by Django 2.2 on 2020-05-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
