# Generated by Django 2.2 on 2020-05-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20200507_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminder',
            new_name='Task',
        ),
    ]
