# Generated by Django 2.2 on 2020-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_auto_20200507_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('creationTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('dueTimeStamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
