# Generated by Django 2.2 on 2020-05-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0010_auto_20200507_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='dueTimeStamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
